#!/bin/bash
# Script para mostrar información del proyecto
clear
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║   📊 CALCULADORA DE BONOS SOBERANOS ARGENTINOS               ║"
echo "║                                                                ║"
echo "║   ✨ Proyecto Completado - Listo para Usar                   ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📂 ESTRUCTURA DEL PROYECTO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "CalculadoraBonosArgentinos/"
echo "│"
echo "├── 💾 BACKEND"
echo "│   ├── main.py              (223 línes) ← Servidor Flask + SQLite"
echo "│   ├── config.py            (42 líneas) ← Configuración personalizable"
echo "│   └── test_calculos.py     (95 líneas) ← Pruebas automatizadas"
echo "│"
echo "├── 🎨 FRONTEND"
echo "│   └── templates/"
echo "│       └── index.html       (450 líneas) ← Interface HTML/CSS/JS"
echo "│"
echo "├── 📦 DEPENDENCIAS"
echo "│   └── requirements.txt     ← Flask 2.3.3"
echo "│"
echo "├── 🔧 INSTALADORES"
echo "│   ├── install.sh           ← Para Linux/Mac"
echo "│   └── install.bat          ← Para Windows"
echo "│"
echo "├── 📖 DOCUMENTACIÓN"
echo "│   ├── INDEX.md             ← Índice principal (COMIENZA AQUÍ)"
echo "│   ├── README.md            ← Documentación completa"
echo "│   ├── QUICKSTART.md        ← Guía rápida (2 minutos)"
echo "│   ├── EXAMPLES.md          ← Casos de uso reales"
echo "│   ├── VIDEO_TUTORIAL.md    ← Flujo visual y guion"
echo "│   ├── CHANGELOG.md         ← Historial y mejoras"
echo "│   └── .gitignore           ← Config para Git"
echo "│"
echo "└── 📊 BASE DE DATOS (se crea automáticamente)"
echo "    └── bonos_simulaciones.db"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 PASOS PARA COMENZAR:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  INSTALAR DEPENDENCIAS"
echo "    ┌─────────────────────────────────────────────────────────┐"
echo "    │ $ bash install.sh          (Linux/Mac)                  │"
echo "    │ O                                                       │"
echo "    │ $ install.bat              (Windows)                   │"
echo "    └─────────────────────────────────────────────────────────┘"
echo ""
echo "2️⃣  EJECUTAR LA APLICACIÓN"
echo "    ┌─────────────────────────────────────────────────────────┐"
echo "    │ $ python main.py                                        │"
echo "    │                                                         │"
echo "    │    * Running on http://0.0.0.0:5000                    │"
echo "    │    * Debug mode: on                                    │"
echo "    └─────────────────────────────────────────────────────────┘"
echo ""
echo "3️⃣  ABRIR EN NAVEGADOR"
echo "    ┌─────────────────────────────────────────────────────────┐"
echo "    │ PC Local:     http://localhost:5000                     │"
echo "    │ Android:      http://192.168.X.X:5000                  │"
echo "    │               (reemplaza X.X con tu IP local)          │"
echo "    └─────────────────────────────────────────────────────────┘"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ CARACTERÍSTICAS PRINCIPALES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Calcula automáticamente:"
echo "   • Rendimiento del PR17 (tasa fija)"
echo "   • Rendimiento del Dual (dólar + paridad)"
echo "   • Cuál activo rinde más"
echo "   • Precio de Break-Even del dólar"
echo ""
echo "✅ Historial completo:"
echo "   • Todas las simulaciones guardadas en SQLite"
echo "   • Exportar a CSV para análisis en Excel"
echo "   • Acceso desde cualquier dispositivo"
echo ""
echo "✅ Interfaz intuitiva:"
echo "   • Formulario simple (4 campos)"
echo "   • Diseño responsive (Mobile-First)"
echo "   • Resultados visuales claros"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 DOCUMENTACIÓN POR NIVEL:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔰 PRINCIPIANTE"
echo "   1. Lee: QUICKSTART.md (5 minutos)"
echo "   2. Ejecuta: bash install.sh"
echo "   3. Abre: http://localhost:5000"
echo ""
echo "📚 USUARIO INTERMEDIO"
echo "   1. Lee: EXAMPLES.md (10 minutos)"
echo "   2. Prueba los casos de uso"
echo "   3. Experimenta con valores propios"
echo "   4. Exporta historial a CSV"
echo ""
echo "🔬 USUARIO AVANZADO"
echo "   1. Lee: README.md (20 minutos)"
echo "   2. Modifica: config.py para personalizar"
echo "   3. Analiza: main.py para entender la lógica"
echo "   4. Extiende: Agrega nuevos bonos o funciones"
echo ""
echo "👨‍🏫 DESARROLLADOR"
echo "   1. Lee: main.py (comentarios claros)"
echo "   2. Prueba: python test_calculos.py"
echo "   3. Mejora: Agrega gráficos, API real, etc."
echo "   4. Contribuye: Tu versión mejorada"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 EJEMPLO RÁPIDO (30 segundos):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Tienes $100.000 USD y preguntas:"
echo "  ¿Compro PR17 (42.5%) o DUAL (18.5% + dólar)?"
echo ""
echo "INGRESÁS:"
echo "  • Dólar Hoy: $1.045"
echo "  • Predicción Diciembre: $1.200"
echo "  • TIR PR17: 42.5%"
echo "  • Paridad Dual: 18.5%"
echo ""
echo "OBTENÉS:"
echo "  • PR17 rinde:        42.50%"
echo "  • DUAL rinde:        33.14%"
echo "  • 🎯 Mejor opción:    PR17"
echo "  • Break-Even:        $1.234,56"
echo ""
echo "CONCLUSIÓN:"
echo "  Con tu predicción de dólar a $1.200, PR17 es mejor."
echo "  Si dólar llega a $1.234,56 o más, entonces DUAL sería mejor."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 ESTADÍSTICAS DEL PROYECTO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Líneas de código:        ~700"
echo "  Funciones Python:        10"
echo "  Endpoints API:           4"
echo "  Archivos de doc:         6"
echo "  Tiempo aprendizaje:      ~10 minutos"
echo "  Tiempo desarrollo:       ~2 horas"
echo "  Tamaño total:            ~100 KB"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  NOTAS IMPORTANTES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔐 Privacidad:"
echo "   • Totalmente local, no envía datos a internet"
echo "   • Base de datos SQLite en tu PC"
echo "   • Código abierto, puedes revisar todo"
echo ""
echo "⚠️  Legal:"
echo "   • NO es asesoría financiera"
echo "   • Úsalo como herramienta educativa"
echo "   • Tu responsabilidad realizar Due Diligence"
echo ""
echo "💡 Tips:"
echo "   • Prueba varios escenarios de dólar"
echo "   • Guarda tu historial para análisis"
echo "   • Exporta a CSV para presentaciones"
echo "   • Revisa periódicamente (variables cambian)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎓 APRENDE MÁS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Documentación recomendada en ESTE ORDEN:"
echo ""
echo "  1️⃣  INDEX.md              ← Visión general (2 min)"
echo "  2️⃣  QUICKSTART.md         ← Comienza ya (2 min)"
echo "  3️⃣  EXAMPLES.md           ← Casos reales (10 min)"
echo "  4️⃣  README.md             ← Detalles completos (15 min)"
echo "  5️⃣  VIDEO_TUTORIAL.md     ← Flujo visual (5 min)"
echo "  6️⃣  config.py             ← Personalización"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ PRÓXIMO PASO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  👉 Lee:     cat INDEX.md"
echo "  👉 O abre:  INDEX.md en tu editor"
echo "  👉 O ejecuta: bash install.sh"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║ ¡Listo para invertir de forma inteligente! 🚀                ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
